.travis.yml: Force upgrade setuptools
The version of setuptools in the Travis virtualenv is old (44.1.1) and
causes tox .package get-build-requires to fail with:

    running egg_info
    error: 'egg_base' must be a directory name (got `src`)

Reinstall to avoid the issue.

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>