.github: Exclude Python 3.4 on Windows
setup-python does not support Python 3.4 on Windows and fails with:

    Version 3.4 was not found in the local cache
    Error: Version 3.4 with arch x64 not found
    The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>