requirements-dev: Add pygments for pyroma/setup.py
`./setup.py check --restructuredtext --strict` (which is run by pyroma)
requires pygments in order to avoid errors such as:

    warning: check: Cannot analyze code. Pygments package not found. (line 38)

    error: Please correct your package.

Include it in the dev dependencies.

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>